/**
 * Canonical hypertrophy program: 4 days, order_index 1–4.
 * rep_min / rep_max are the stored rep range (same as repRangeMin / repRangeMax in product language).
 */

export type HypertrophyTemplateSetDef = {
  set_number: number;
  target_weight: number | null;
  target_reps: number;
  rest_seconds: number;
  is_bodyweight?: boolean;
  note?: string | null;
  variation?: string | null;
};

export type HypertrophyExerciseDef = {
  id: string;
  exercise_name: string;
  order_index: number;
  target_sets: number;
  repRangeMin: number;
  repRangeMax: number;
  target_weight: number;
  cue_text: string | null;
  rest_seconds: number;
  increment_lbs: number;
  progression_rule: "double_progression" | "hold_then_progress" | "deload_on_failure";
  is_compound: boolean;
  template_sets: HypertrophyTemplateSetDef[];
};

export type HypertrophyDayDef = {
  id: string;
  name: string;
  order_index: number;
  exercises: HypertrophyExerciseDef[];
};

function uniformSets(
  count: number,
  rest: number,
  targetWeight: number | null,
  targetReps: number,
  isBodyweight = false,
): HypertrophyTemplateSetDef[] {
  return Array.from({ length: count }, (_, i) => ({
    set_number: i + 1,
    target_weight: targetWeight,
    target_reps: targetReps,
    rest_seconds: rest,
    is_bodyweight: isBodyweight,
    note: null,
    variation: null,
  }));
}

/** Program day order: UPPER A → LOWER A → UPPER B → LOWER B */
export const HYPERTROPHY_DAYS: HypertrophyDayDef[] = [
  {
    id: "hypertrophy-upper-a",
    name: "UPPER A",
    order_index: 1,
    exercises: [
      {
        id: "tmpl-ua-bench-barbell",
        exercise_name: "Bench Press (Barbell)",
        order_index: 1,
        target_sets: 4,
        repRangeMin: 5,
        repRangeMax: 8,
        target_weight: 185,
        cue_text: null,
        rest_seconds: 90,
        increment_lbs: 5,
        progression_rule: "double_progression",
        is_compound: true,
        template_sets: uniformSets(4, 90, 185, 8),
      },
      {
        id: "tmpl-ua-seated-row",
        exercise_name: "Seated Row (Cable)",
        order_index: 2,
        target_sets: 3,
        repRangeMin: 8,
        repRangeMax: 12,
        target_weight: 120,
        cue_text: null,
        rest_seconds: 75,
        increment_lbs: 5,
        progression_rule: "double_progression",
        is_compound: true,
        template_sets: uniformSets(3, 75, 120, 12),
      },
      {
        id: "tmpl-ua-incline-db",
        exercise_name: "Incline Bench Press (Dumbbell)",
        order_index: 3,
        target_sets: 3,
        repRangeMin: 8,
        repRangeMax: 10,
        target_weight: 55,
        cue_text: null,
        rest_seconds: 90,
        increment_lbs: 5,
        progression_rule: "double_progression",
        is_compound: true,
        template_sets: uniformSets(3, 90, 55, 10),
      },
      {
        id: "tmpl-ua-lateral-raise",
        exercise_name: "Lateral Raise (Dumbbell)",
        order_index: 4,
        target_sets: 3,
        repRangeMin: 12,
        repRangeMax: 15,
        target_weight: 20,
        cue_text: null,
        rest_seconds: 60,
        increment_lbs: 2.5,
        progression_rule: "hold_then_progress",
        is_compound: false,
        template_sets: uniformSets(3, 60, 20, 15),
      },
      {
        id: "tmpl-ua-tri-pushdown",
        exercise_name: "Triceps Pushdown (Cable)",
        order_index: 5,
        target_sets: 3,
        repRangeMin: 10,
        repRangeMax: 12,
        target_weight: 45,
        cue_text: null,
        rest_seconds: 75,
        increment_lbs: 5,
        progression_rule: "hold_then_progress",
        is_compound: false,
        template_sets: uniformSets(3, 75, 45, 12),
      },
    ],
  },
  {
    id: "hypertrophy-lower-a-knee",
    name: "LOWER A (Knee Friendly)",
    order_index: 2,
    exercises: [
      {
        id: "tmpl-la-leg-press",
        exercise_name: "Leg Press",
        order_index: 1,
        target_sets: 4,
        repRangeMin: 10,
        repRangeMax: 12,
        target_weight: 270,
        cue_text: null,
        rest_seconds: 70,
        increment_lbs: 10,
        progression_rule: "double_progression",
        is_compound: true,
        template_sets: uniformSets(4, 70, 270, 12),
      },
      {
        id: "tmpl-la-glute-bridge",
        exercise_name: "Glute Bridge",
        order_index: 2,
        target_sets: 3,
        repRangeMin: 8,
        repRangeMax: 12,
        target_weight: 95,
        cue_text: "2–3 second squeeze at top",
        rest_seconds: 55,
        increment_lbs: 5,
        progression_rule: "double_progression",
        is_compound: true,
        template_sets: uniformSets(3, 55, 95, 12),
      },
      {
        id: "tmpl-la-back-extension",
        exercise_name: "Back Extension",
        order_index: 3,
        target_sets: 3,
        repRangeMin: 12,
        repRangeMax: 15,
        target_weight: 45,
        cue_text: null,
        rest_seconds: 80,
        increment_lbs: 5,
        progression_rule: "hold_then_progress",
        is_compound: false,
        template_sets: uniformSets(3, 80, 45, 15),
      },
      {
        id: "tmpl-la-leg-extension",
        exercise_name: "Leg Extension (Machine)",
        order_index: 4,
        target_sets: 3,
        repRangeMin: 10,
        repRangeMax: 15,
        target_weight: 65,
        cue_text: null,
        rest_seconds: 80,
        increment_lbs: 5,
        progression_rule: "hold_then_progress",
        is_compound: false,
        template_sets: uniformSets(3, 80, 65, 15),
      },
      {
        id: "tmpl-la-lying-leg-curl",
        exercise_name: "Lying Leg Curl (Machine)",
        order_index: 5,
        target_sets: 3,
        repRangeMin: 10,
        repRangeMax: 15,
        target_weight: 55,
        cue_text: null,
        rest_seconds: 55,
        increment_lbs: 5,
        progression_rule: "hold_then_progress",
        is_compound: false,
        template_sets: uniformSets(3, 55, 55, 15),
      },
      {
        id: "tmpl-la-knee-raise",
        exercise_name: "Knee Raise (Captain's Chair)",
        order_index: 6,
        target_sets: 3,
        repRangeMin: 12,
        repRangeMax: 15,
        target_weight: 0,
        cue_text: null,
        rest_seconds: 75,
        increment_lbs: 0,
        progression_rule: "hold_then_progress",
        is_compound: false,
        template_sets: uniformSets(3, 75, null, 15, true),
      },
      {
        id: "tmpl-la-cable-twist",
        exercise_name: "Cable Twist",
        order_index: 7,
        target_sets: 3,
        repRangeMin: 12,
        repRangeMax: 15,
        target_weight: 25,
        cue_text: "12–15 reps per side",
        rest_seconds: 55,
        increment_lbs: 2.5,
        progression_rule: "hold_then_progress",
        is_compound: false,
        template_sets: uniformSets(3, 55, 25, 15),
      },
    ],
  },
  {
    id: "hypertrophy-upper-b",
    name: "UPPER B",
    order_index: 3,
    exercises: [
      {
        id: "tmpl-ub-lat-pulldown",
        exercise_name: "Lat Pulldown (Cable)",
        order_index: 1,
        target_sets: 3,
        repRangeMin: 8,
        repRangeMax: 12,
        target_weight: 140,
        cue_text: "Neutral grip",
        rest_seconds: 75,
        increment_lbs: 5,
        progression_rule: "double_progression",
        is_compound: true,
        template_sets: uniformSets(3, 75, 140, 12),
      },
      {
        id: "tmpl-ub-bench-db",
        exercise_name: "Bench Press (Dumbbell)",
        order_index: 2,
        target_sets: 3,
        repRangeMin: 8,
        repRangeMax: 10,
        target_weight: 60,
        cue_text: "Pause at bottom only",
        rest_seconds: 90,
        increment_lbs: 5,
        progression_rule: "double_progression",
        is_compound: true,
        template_sets: uniformSets(3, 90, 60, 10),
      },
      {
        id: "tmpl-ub-seated-row",
        exercise_name: "Seated Row (Cable)",
        order_index: 3,
        target_sets: 3,
        repRangeMin: 8,
        repRangeMax: 12,
        target_weight: 120,
        cue_text: null,
        rest_seconds: 75,
        increment_lbs: 5,
        progression_rule: "double_progression",
        is_compound: true,
        template_sets: uniformSets(3, 75, 120, 12),
      },
      {
        id: "tmpl-ub-hammer-curl",
        exercise_name: "Hammer Curl (Dumbbell)",
        order_index: 4,
        target_sets: 3,
        repRangeMin: 8,
        repRangeMax: 10,
        target_weight: 35,
        cue_text: null,
        rest_seconds: 75,
        increment_lbs: 2.5,
        progression_rule: "hold_then_progress",
        is_compound: false,
        template_sets: uniformSets(3, 75, 35, 10),
      },
      {
        id: "tmpl-ub-tri-pushdown-straight",
        exercise_name: "Triceps Pushdown (Cable - Straight Bar)",
        order_index: 5,
        target_sets: 3,
        repRangeMin: 10,
        repRangeMax: 12,
        target_weight: 45,
        cue_text: null,
        rest_seconds: 75,
        increment_lbs: 5,
        progression_rule: "hold_then_progress",
        is_compound: false,
        template_sets: uniformSets(3, 75, 45, 12),
      },
      {
        id: "tmpl-ub-reverse-fly",
        exercise_name: "Reverse Fly (Dumbbell)",
        order_index: 6,
        target_sets: 3,
        repRangeMin: 12,
        repRangeMax: 15,
        target_weight: 15,
        cue_text: null,
        rest_seconds: 60,
        increment_lbs: 2.5,
        progression_rule: "hold_then_progress",
        is_compound: false,
        template_sets: uniformSets(3, 60, 15, 15),
      },
    ],
  },
  {
    id: "hypertrophy-lower-b",
    name: "LOWER B",
    order_index: 4,
    exercises: [
      {
        id: "tmpl-lb-rdl",
        exercise_name: "Romanian Deadlift (Barbell)",
        order_index: 1,
        target_sets: 4,
        repRangeMin: 6,
        repRangeMax: 10,
        target_weight: 185,
        cue_text: null,
        rest_seconds: 80,
        increment_lbs: 5,
        progression_rule: "double_progression",
        is_compound: true,
        template_sets: uniformSets(4, 80, 185, 10),
      },
      {
        id: "tmpl-lb-hip-thrust",
        exercise_name: "Hip Thrust (Barbell)",
        order_index: 2,
        target_sets: 3,
        repRangeMin: 8,
        repRangeMax: 12,
        target_weight: 185,
        cue_text: null,
        rest_seconds: 90,
        increment_lbs: 10,
        progression_rule: "double_progression",
        is_compound: true,
        template_sets: uniformSets(3, 90, 185, 12),
      },
      {
        id: "tmpl-lb-lying-leg-curl",
        exercise_name: "Lying Leg Curl (Machine)",
        order_index: 3,
        target_sets: 3,
        repRangeMin: 10,
        repRangeMax: 15,
        target_weight: 55,
        cue_text: null,
        rest_seconds: 55,
        increment_lbs: 5,
        progression_rule: "hold_then_progress",
        is_compound: false,
        template_sets: uniformSets(3, 55, 55, 15),
      },
      {
        id: "tmpl-lb-leg-extension",
        exercise_name: "Leg Extension (Machine)",
        order_index: 4,
        target_sets: 3,
        repRangeMin: 10,
        repRangeMax: 15,
        target_weight: 65,
        cue_text: null,
        rest_seconds: 55,
        increment_lbs: 5,
        progression_rule: "hold_then_progress",
        is_compound: false,
        template_sets: uniformSets(3, 55, 65, 15),
      },
      {
        id: "tmpl-lb-leg-press",
        exercise_name: "Leg Press",
        order_index: 5,
        target_sets: 3,
        repRangeMin: 10,
        repRangeMax: 15,
        target_weight: 290,
        cue_text: null,
        rest_seconds: 70,
        increment_lbs: 10,
        progression_rule: "double_progression",
        is_compound: true,
        template_sets: uniformSets(3, 70, 290, 15),
      },
      {
        id: "tmpl-lb-calf-raise",
        exercise_name: "Standing Calf Raise (Dumbbell)",
        order_index: 6,
        target_sets: 3,
        repRangeMin: 12,
        repRangeMax: 20,
        target_weight: 40,
        cue_text: null,
        rest_seconds: 45,
        increment_lbs: 5,
        progression_rule: "hold_then_progress",
        is_compound: false,
        template_sets: uniformSets(3, 45, 40, 20),
      },
      {
        id: "tmpl-lb-hanging-leg-raise",
        exercise_name: "Hanging Leg Raise",
        order_index: 7,
        target_sets: 3,
        repRangeMin: 10,
        repRangeMax: 15,
        target_weight: 0,
        cue_text: 'Think "curl spine"',
        rest_seconds: 45,
        increment_lbs: 0,
        progression_rule: "hold_then_progress",
        is_compound: false,
        template_sets: uniformSets(3, 45, null, 15, true),
      },
    ],
  },
];

export const MOCK_PROGRAM_NAME = "Hypertrophy";
export const MOCK_PROGRAM_GOAL =
  "Four-day upper/lower split (UPPER A → LOWER A → UPPER B → LOWER B). Progression is exercise-specific.";
