export const MOCK_PROGRAM_DAYS = [
  {
    id: "demo-upper-a",
    name: "Upper A",
    order_index: 1,
    template_exercises: [
      {
        id: "demo-bench",
        exercise_name: "Barbell Bench Press",
        order_index: 1,
        target_sets: 3,
        rep_min: 6,
        rep_max: 10,
        target_weight: 135,
        cue_text: "Pause on chest",
        rest_seconds: 150,
        increment_lbs: 5,
        progression_rule: "double_progression",
      },
      {
        id: "demo-row",
        exercise_name: "Chest Supported Row",
        order_index: 2,
        target_sets: 3,
        rep_min: 8,
        rep_max: 12,
        target_weight: 95,
        cue_text: "Drive elbows low",
        rest_seconds: 120,
        increment_lbs: 5,
        progression_rule: "hold_then_progress",
      },
    ],
  },
  {
    id: "demo-lower-a",
    name: "Lower A",
    order_index: 2,
    template_exercises: [],
  },
  {
    id: "demo-upper-b",
    name: "Upper B",
    order_index: 3,
    template_exercises: [],
  },
  {
    id: "demo-lower-b",
    name: "Lower B",
    order_index: 4,
    template_exercises: [],
  },
  {
    id: "demo-deload",
    name: "Deload",
    order_index: 5,
    template_exercises: [],
  },
] as const;
